# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Midnight Musings 
# email: olakra@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog space where I explore and share thoughts on 
  the world of software engineering, leadership in tech, and the dynamic 
  journey of entrepreneurship. Here, you'll find thoughtful reflections on 
  everything from mastering the art of code to navigating the complexities of 
  management, along with broader musings on life, productivity, and innovation. 
  Whether you're a developer, aspiring leader, or someone seeking inspiration 
  in your own professional journey, this blog aims to offer fresh perspectives, 
  actionable advice, and a bit of curiosity-driven exploration. Let’s learn, grow, 
  and thrive together!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# witter_username: olakra
# github_username:  olakra

# Build settings
markdown: kramdown
theme: minima
#remote_theme: daviddarnes/alembic@main

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-livereload
  - jekyll-remote-theme
  - jemoji


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
# fonts:
#   preconnect_urls:
#     - https://fonts.gstatic.com
#   font_urls:
#     - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap


# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages